### ISSUE TITLE
Fix deploying

### ISSUE THREAD

**Issue by sanikolaev** [manticoresoftware/manticoresearch-language-packs#3]
Looks like the CI which deploys packages in this repo is outdated. I see 2 issues:
1. https://github.com/manticoresoftware/manticoresearch-language-packs/blob/9be63f0d2362b7dd4fe758701bf26239c6b0ac16/.github/workflows/package.yml#L82 - should be not "self-hosted"
2. https://github.com/manticoresoftware/manticoresearch-language-packs/blob/9be63f0d2362b7dd4fe758701bf26239c6b0ac16/.github/workflows/package.yml#L155 - broken link to e.g. https://raw.githubusercontent.com/manticoresoftware/repo_scripts/main/upload_repo_deb

The task is to update the CI similarly to how deployment is done in other repos.

**Comment by KlimTodrik** [comment]
Fixed in https://github.com/manticoresoftware/manticoresearch-language-packs/pull/4
